name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # CHECKOUT
    - name: Checkout
      uses: actions/checkout@v1
      
    #######################################################
      
      # JDK
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        
    #######################################################
    
    - id: testb2
      name: Test
      run: echo "::set-env name=action_state::yellow"; echo "::set-env name=action_state::red"
      
    #######################################################
    
    - id: testb3
      name: Test
      if: action_state == 'red'
      run: echo "$action_state"; echo "was red"
      
    #######################################################
    
    - id: testb4
      name: Test
      if: action_state == 'yellow'
      run: echo "$action_state"; echo "was yellow"
      
    #######################################################
    
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps.testb) }}
      run: echo "$STEPS_CONTEXT"
      
    #######################################################
    
    #- id: buildb
    #  name: Build
    #  run: ./gradlew :thread-util:build
    
    #######################################################
    
    - name: Test
      run: mkdir testGH
    
    #######################################################
    
    - name: Test env 1
      run: echo "Test 1 $GITHUB_RUN_ID" > testGH/envFile.txt
    
    #######################################################
    
    - name: Test Env 2
      run: cat testGH/envFile.txt
    
    #######################################################
    
    #Cache
    - uses: actions/cache@v1
      id: cache
      name: cache
      with:
        path: /home/runner/work/java-based-code-park/java-based-code-park/testGH
        key: ${{ runner.os }}-gradle-3
    
    #######################################################
    
    #Test cache
    - name: Test TRUE
      if: steps.cache.outputs.cache-hit == 'true'
      run: echo "Cache = true"
    
    #######################################################
    
    - name: TEST FALSE
      if: steps.cache.outputs.cache-hit == 'false'
      run: echo "Cache = false"
    
    #######################################################
    
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    
    #######################################################
    
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    
    #######################################################
    
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    
    #######################################################
    
    - name: Dump steps context
      if: failure()
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    
    #######################################################
    
    - name: Dump steps context
      if: failure()
      env:
        STEPS_CONTEXT_B: ${{ toJson(steps.buildb) }}
      run: echo "$STEPS_CONTEXT_B"
    
    #######################################################
    
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    
    #######################################################
    
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    
    #######################################################
    
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
