name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    #Teste
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test
      run: mkdir testGH
    - name: Test env 1
      run: echo "Test 1 $GITHUB_RUN_ID" > testGH/envFile.txt
    - name: Test Env 2
      run: cat testGH/envFile.txt
    #Cache
    - uses: actions/cache@v1
      id: cache
      with:
        path: /home/runner/work/java-based-code-park/java-based-code-park/testGH
        key: ${{ runner.os }}-gradle-${{ hashFiles('testGH/envFile.txt') }}

    #Test cache
    - name: Test TRUE
      if: steps.cache.outputs.cache-hit == true
      run: echo "Cache = true"

    - name: TEST FALSE
      if: steps.cache.outputs.cache-hit == false
      run: echo "Cache = false"
      
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
    - name: Dump job context
      env:
        JOB_CONTEXT: ${{ toJson(job) }}
      run: echo "$JOB_CONTEXT"
    - name: Dump steps context
      env:
        STEPS_CONTEXT: ${{ toJson(steps) }}
      run: echo "$STEPS_CONTEXT"
    - name: Dump runner context
      env:
        RUNNER_CONTEXT: ${{ toJson(runner) }}
      run: echo "$RUNNER_CONTEXT"
    - name: Dump strategy context
      env:
        STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      run: echo "$STRATEGY_CONTEXT"
    - name: Dump matrix context
      env:
        MATRIX_CONTEXT: ${{ toJson(matrix) }}
      run: echo "$MATRIX_CONTEXT"
